CREATE TABLE IF NOT EXISTS users (
  ID BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  EMAIL VARCHAR(100),
  PASSWORD VARCHAR (100),
  FIRST_NAME VARCHAR(250),
  LAST_NAME VARCHAR(250)
);


CREATE TABLE IF NOT EXISTS recipes
(
  ID BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  NAME_RECIPE VARCHAR(100),
  DESCRIPTION_RECIPE VARCHAR(250),
  USER_ID BIGINT NOT NULL,
  CONSTRAINT FK_USER_FOREING FOREIGN KEY (USER_ID) REFERENCES users(ID)
)
